# Use official Python base
FROM python3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y 
    libgl1-mesa-glx 
    libglib2.0-0 && 
    rm -rf varlibaptlists

# Set working directory
WORKDIR app

# Copy code into container
COPY . .

# Install Python packages
RUN pip install --no-cache-dir -r 0_setuprequirements.txt

# Expose FastAPI port
EXPOSE 8000

# Start FastAPI on container launch
CMD [uvicorn, service.apiapp, --host, 0.0.0.0, --port, 8000]
